services:
  # Enhanced S5.js mock server only
  enhanced-s5:
    build:
      context: /root/dev/Fabstir/partners/S5/GitHub/s5.js
      dockerfile: Dockerfile.mock
    container_name: enhanced-s5-mock
    ports:
      - "5524:5524"
    environment:
      - PORT=5524
      - NODE_ENV=test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5524/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
