#!/usr/bin/env python3
# Copyright (c) 2025 Fabstir
# SPDX-License-Identifier: BUSL-1.1
"""Derive the Phase B (video) compose from the rehearsed base compose, so the two never
drift (docs/development/PLAN-PHASE5-RUN2-VIDEO.md D1). The ONLY differences: three LTX
services (ltx-init, ltx-weights-init, ltx-sidecar), four volumes, and on the node
COMFY_URL set, TEMPLATE_DIR added, the templates volume mounted read-only and a
depends_on on ltx-init. The secrets (allowed_envs) are untouched: same 15 names, same
values, so Phase B's Update Code needs no re-paste.

Usage (node repo root):
  python3 deployment/phala/run2/make_video_compose.py sha256:<ltx-sidecar-cvm digest>
Writes deployment/phala/run2/compose.gpu-run2-video.yml and asserts that it equals the
base plus exactly those keys.
"""
import copy, pathlib, re, sys, yaml

here = pathlib.Path(__file__).parent
BASE = here / "compose.gpu-run2.yml"
OUT = here / "compose.gpu-run2-video.yml"

digest = sys.argv[1] if len(sys.argv) > 1 else "sha256:REPLACE_WITH_LTX_SIDECAR_DIGEST"
if len(sys.argv) > 1 and not re.fullmatch(r"sha256:[0-9a-f]{64}", digest):
    sys.exit("digest must be sha256:<64 lowercase hex>")
IMAGE = f"ewr.vultrcr.com/fabstir/ltx-sidecar-cvm@{digest}"

base = yaml.safe_load(BASE.read_text())
d = copy.deepcopy(base)
svc = d["services"]

node = svc["llm-node"]
assert node["environment"]["COMFY_URL"] == "", "base must have LTX off"
node["environment"]["COMFY_URL"] = "http://ltx-sidecar:8188"
node["environment"]["TEMPLATE_DIR"] = "/opt/fabstir/ltx-templates"
node["volumes"].append("ltx-templates:/opt/fabstir/ltx-templates:ro")
node["depends_on"]["ltx-init"] = {"condition": "service_completed_successfully"}

svc["ltx-init"] = {
    "image": IMAGE,
    "container_name": "ltx-init",
    "user": "0",
    "restart": "no",  # as template-init (no network use; no network_mode novelty on dstack)
    # Always exits 0 (a failed copy = no LTX this boot, never no node).
    "entrypoint": ["/usr/local/bin/ltx-cvm-init.sh", "templates"],
    "volumes": ["ltx-templates:/opt/fabstir/ltx-templates"],
}
svc["ltx-weights-init"] = {
    "image": IMAGE,
    "container_name": "ltx-weights-init",
    "user": "0",
    "restart": "on-failure:3",
    "entrypoint": ["/usr/local/bin/ltx-cvm-init.sh", "weights"],
    "volumes": ["ltx-weights:/models"],
}
svc["ltx-sidecar"] = {
    "image": IMAGE,
    "container_name": "ltx-sidecar",
    "restart": "unless-stopped",
    # Wait for the weights marker, then the image's own `python main.py` with the flags
    # below ($$ is compose's escape for a literal $). Under GPU CC mode host-memory
    # registration is not allowed: --disable-pinned-memory, and --highvram also turns
    # ComfyUI's dynamic-VRAM manager off; --verbose WARNING keeps the public log quiet.
    "entrypoint": ["/bin/sh", "-c",
                   "until [ -f /opt/ComfyUI/models/.complete-ltx ]; do sleep 15; done; "
                   "exec python main.py \"$$@\"", "wait-for-weights"],
    "command": ["--listen", "0.0.0.0", "--port", "8188",
                "--output-directory", "/opt/ComfyUI/output",
                "--highvram", "--disable-pinned-memory", "--verbose", "WARNING"],
    "runtime": "nvidia",
    "shm_size": "16g",
    "environment": {
        "NVIDIA_VISIBLE_DEVICES": "all",
        "NVIDIA_DRIVER_CAPABILITIES": "compute,utility",
        "PYTORCH_NO_CUDA_MEMORY_CACHING": "1",
    },
    "volumes": ["ltx-weights:/opt/ComfyUI/models:ro",
                "ltx-input:/opt/ComfyUI/input",
                "ltx-output:/opt/ComfyUI/output"],
    "healthcheck": {
        "test": ["CMD", "curl", "-f", "http://localhost:8188/system_stats"],
        "interval": "30s", "timeout": "10s", "start_period": "900s", "retries": 3,
    },
}
vols = d["volumes"]
vols["ltx-templates"] = None
vols["ltx-weights"] = None
# RAM-backed: uploaded inputs and rendered frames (plaintext) never touch the disk;
# nothing deletes them, so the caps bound a long session.
vols["ltx-input"] = {"driver_opts": {"type": "tmpfs", "device": "tmpfs", "o": "size=8g"}}
vols["ltx-output"] = {"driver_opts": {"type": "tmpfs", "device": "tmpfs", "o": "size=16g"}}

# The diff assertion: strip exactly what was added/changed and compare with the base.
check = copy.deepcopy(d)
for k in ("ltx-init", "ltx-weights-init", "ltx-sidecar"):
    del check["services"][k]
for k in ("ltx-templates", "ltx-weights", "ltx-input", "ltx-output"):
    del check["volumes"][k]
cn = check["services"]["llm-node"]
cn["environment"]["COMFY_URL"] = ""
del cn["environment"]["TEMPLATE_DIR"]
cn["volumes"].remove("ltx-templates:/opt/fabstir/ltx-templates:ro")
del cn["depends_on"]["ltx-init"]
assert check == base, "the video variant differs from the base beyond the planned keys"

header = ("# GENERATED by make_video_compose.py from compose.gpu-run2.yml. Do not edit; regenerate.\n"
          "# Phase 5 run 2, Phase B (video): the base compose + the LTX sidecar\n"
          "# (docs/development/PLAN-PHASE5-RUN2-VIDEO.md). Deployed by Update Code AFTER the\n"
          "# base demo, under policy v5; same 15 secrets as the base.\n")
OUT.write_text(header + yaml.safe_dump(d, sort_keys=False, width=100))
print("wrote", OUT, "image", IMAGE)
if "REPLACE_WITH" in IMAGE:
    print("WARNING: placeholder digest; pass the pushed ltx-sidecar-cvm digest before predicting")
