#!/usr/bin/env python3
# Copyright (c) 2025 Fabstir
# SPDX-License-Identifier: BUSL-1.1
"""Derive the 3XS-Z dress-rehearsal compose from compose.gpu-run2.yml, so the two
never drift. The ONLY differences: the attested load path is off (no dstack socket
off-CVM; the TEE path was proven on the H200 on 2026-09-23), the node loads the
local Qwen3.8 GGUF instead, and the secrets come from a local .env. Everything new
in run 2 (template/weights init, trainer, image sidecar, s5-bridge, volumes, env)
runs exactly as it will in the CVM.

Usage (node repo root): python3 deployment/phala/run2/make_rehearsal_compose.py [--video]
Writes deployment/phala/run2/compose.rehearsal-3xsz.yml, or with --video
compose.rehearsal-3xsz-video.yml from the Phase B variant (PLAN-PHASE5-RUN2-VIDEO.md D10:
the LTX weights come from a read-only bind mount of 3XS-Z's own copy, LTX_MODELS_DIR in
./.env, instead of the in-CVM download, and the sidecar runs the image's own entrypoint).
"""
import pathlib, sys, yaml

here = pathlib.Path(__file__).parent
VIDEO = "--video" in sys.argv[1:]
SRC = "compose.gpu-run2-video.yml" if VIDEO else "compose.gpu-run2.yml"
OUT = "compose.rehearsal-3xsz-video.yml" if VIDEO else "compose.rehearsal-3xsz.yml"
d = yaml.safe_load((here / SRC).read_text())
node = d["services"]["llm-node"]
env = node["environment"]
for k in [k for k in env if k.startswith("TEE_")]:
    del env[k]  # live.rs refuses TEE_MODEL_ID with the flag off; the rest are dropped for clarity
env["HOST_TEE_ENABLED"] = "false"
env["MODEL_PATH"] = "/app/models/Qwen3.8-27B-Q8_0.gguf"
node["volumes"] = [v for v in node["volumes"] if "dstack.sock" not in v]
node["volumes"].append("${MODELS_DIR:?host dir holding Qwen3.8-27B-Q8_0.gguf}:/app/models:ro")
# TEST_HOST_1 is registered at http://localhost:8082, so the app dials host port 8082:
# publish the node there. Bring the dev stack DOWN first (docker compose -f
# docker-compose.prod.yml down): it holds port 8082, the same container names
# (s5-bridge, trainer-sidecar, diffusion-sidecar) and VRAM.
node["ports"] = ["8082:8080"]
# A missing secret must fail at `up`, not become a blank string (no :? in the CVM
# compose, where Phala's form supplies them; the rehearsal reads ./.env).
for svc in d["services"].values():
    for k, v in (svc.get("environment") or {}).items():
        for secret in ("HOST_PRIVATE_KEY", "RPC_URL", "S5_SEED_PHRASE"):
            if v == "${%s}" % secret:
                svc["environment"][k] = "${%s:?set %s in deployment/phala/run2/.env}" % (secret, secret)
if VIDEO:
    ltx = d["services"]["ltx-sidecar"]
    assert "ltx-weights:/opt/ComfyUI/models:ro" in ltx["volumes"]
    ltx["volumes"] = ["${LTX_MODELS_DIR:?host dir holding the LTX weights in category folders}"
                      ":/opt/ComfyUI/models:ro" if v == "ltx-weights:/opt/ComfyUI/models:ro" else v
                      for v in ltx["volumes"]]
    del ltx["entrypoint"]  # no marker to wait for: the image's own `python main.py` + command
    del d["services"]["ltx-weights-init"]
    del d["volumes"]["ltx-weights"]
header = ("# GENERATED by make_rehearsal_compose.py from %s. Do not edit;\n" % SRC +
          "# regenerate. 3XS-Z dress rehearsal: TEE off, local GGUF, secrets from ./.env\n"
          "# (HOST_PRIVATE_KEY, RPC_URL, S5_SEED_PHRASE, RUST_LOG, MODELS_DIR).\n")
(here / OUT).write_text(header + yaml.safe_dump(d, sort_keys=False, width=100))
print("wrote", here / OUT)
