// Copyright (c) 2025 Fabstir
// SPDX-License-Identifier: BUSL-1.1
//! T1.1: the node side of the cross-side vector contract. Every file under
//! `tests/training/vectors/` was generated by `scripts/gen_training_vectors.js`
//! (ethers v6 — the TS-side reference); these tests prove the Rust encoders
//! reproduce the SAME bytes, and pin the cross-links between the vector files
//! so a partial regeneration cannot drift them apart. Interface:
//! DESIGN-TRAINING-M0-INTERFACE.md (FROZEN; Status line = version authority).

use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

use ethers::types::{Address, RecoveryMessage, Signature};
use fabstir_llm_node::crypto::proof_signer::sign_eip191_digest;
use fabstir_llm_node::training::attestation::{
    canonical_manifest_bytes, canonical_manifest_sha256, input_commitment, input_commitment_bytes,
    sig_digest, SliceSigFields,
};
use fabstir_llm_node::training::schedule::{slice_deltas, training_tokens};
use fabstir_llm_node::training::types::TrainingJob;
use serde_json::Value;

fn load(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/training/vectors")
        .join(name);
    let raw = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {path:?}: {e}"))
}

fn as_str<'a>(v: &'a Value, ptr: &str) -> &'a str {
    v.pointer(ptr)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("missing string at {ptr}"))
}

fn as_u64(v: &Value, ptr: &str) -> u64 {
    v.pointer(ptr)
        .and_then(Value::as_u64)
        .unwrap_or_else(|| panic!("missing u64 at {ptr}"))
}

// ---------------------------------------------------------------------------
// input-commitment.json — B.4 byte identity (encode bytes AND keccak)
// ---------------------------------------------------------------------------

#[test]
fn input_commitment_vector_bytes_and_hash() {
    let vec = load("input-commitment.json");
    let job: TrainingJob = serde_json::from_value(vec["job"].clone())
        .expect("vector job must deserialise through the wire type");

    let bytes = input_commitment_bytes(&job).expect("encode");
    assert_eq!(
        format!("0x{}", hex::encode(&bytes)),
        as_str(&vec, "/abiEncoded"),
        "abi.encode bytes diverge from the TS reference"
    );
    assert_eq!(
        input_commitment(&job).expect("commitment"),
        as_str(&vec, "/inputCommitment"),
        "inputCommitment keccak diverges from the TS reference"
    );
    // Adversarial values are load-bearing: trailing-zero lr; a seed that is
    // BOTH > u64::MAX and float-lossy (a power of two would survive an f64
    // round-trip — the round-1 review's catch).
    assert_eq!(job.hyper.lr, "0.000200");
    assert!(job.hyper.lr_is_canonical());
    let seed = job.hyper.seed_u256().unwrap();
    assert!(
        seed > ethers::types::U256::from(u64::MAX),
        "seed must exceed u64"
    );
    let seed_f64 = job.hyper.seed.parse::<f64>().unwrap();
    assert_ne!(
        format!("{seed_f64:.0}"),
        job.hyper.seed,
        "seed must NOT survive a float round-trip (power-of-two trap)"
    );
}

/// A.1's numeric wire rule: `null` (the NaN → stringify shape), a MISSING
/// member, and a FLOAT-typed value must all fail deserialisation.
#[test]
fn null_missing_or_float_numeric_member_rejected() {
    let vec = load("input-commitment.json");

    let mut nulled = vec["job"].clone();
    *nulled.pointer_mut("/hyper/rank").unwrap() = Value::Null;
    assert!(
        serde_json::from_value::<TrainingJob>(nulled).is_err(),
        "null rank must fail"
    );

    let mut missing = vec["job"].clone();
    missing.as_object_mut().unwrap().remove("epochs");
    assert!(
        serde_json::from_value::<TrainingJob>(missing).is_err(),
        "missing epochs must fail"
    );

    let mut nulled_u64 = vec["job"].clone();
    *nulled_u64.pointer_mut("/dataset/declaredTokens").unwrap() = Value::Null;
    assert!(
        serde_json::from_value::<TrainingJob>(nulled_u64).is_err(),
        "null declaredTokens must fail"
    );

    for float_val in [3.0_f64, 3.5_f64] {
        let mut floated = vec["job"].clone();
        *floated.pointer_mut("/epochs").unwrap() = serde_json::json!(float_val);
        assert!(
            serde_json::from_value::<TrainingJob>(floated).is_err(),
            "float epochs {float_val} must fail deserialisation into u32"
        );
    }
}

/// The documented protocol posture: unknown keys are TOLERATED (no
/// deny_unknown_fields) — old nodes ignore new optional members.
#[test]
fn unknown_keys_tolerated() {
    let vec = load("input-commitment.json");
    let mut extended = vec["job"].clone();
    extended
        .as_object_mut()
        .unwrap()
        .insert("futureField".into(), serde_json::json!("ignored"));
    extended
        .pointer_mut("/hyper")
        .unwrap()
        .as_object_mut()
        .unwrap()
        .insert("futureKnob".into(), serde_json::json!(7));
    let job: TrainingJob =
        serde_json::from_value(extended).expect("unknown keys must be tolerated");
    assert_eq!(job.epochs, 3);
}

#[test]
fn lr_canonical_form_guard() {
    let vec = load("input-commitment.json");
    let mut job: TrainingJob = serde_json::from_value(vec["job"].clone()).unwrap();
    for bad in ["2e-4", "", ".5", "1.", "0.2.0", "0x1", " 0.2"] {
        job.hyper.lr = bad.to_string();
        assert!(
            !job.hyper.lr_is_canonical(),
            "{bad:?} must be non-canonical"
        );
    }
    for good in ["0.000200", "1", "0.5", "42.000"] {
        job.hyper.lr = good.to_string();
        assert!(job.hyper.lr_is_canonical(), "{good:?} must be canonical");
    }
}

// ---------------------------------------------------------------------------
// slice-schedule.json — B.1 floor rule, all four regimes
// ---------------------------------------------------------------------------

#[test]
fn slice_schedule_vectors() {
    let vec = load("slice-schedule.json");
    let cases = vec["cases"].as_object().expect("cases object");
    assert_eq!(cases.len(), 4, "the interface pins four schedule regimes");
    for (name, case) in cases {
        let declared = as_u64(case, "/declaredTokens");
        let epochs = as_u64(case, "/epochs") as u32;
        let slice_tokens = as_u64(case, "/sliceTokens");
        let total = training_tokens(declared, epochs).expect("in-bounds");
        assert_eq!(total, as_u64(case, "/totalTokens"), "{name}: totalTokens");
        let deltas = slice_deltas(total, slice_tokens).expect("in-bounds schedule");
        assert_eq!(
            deltas.len() as u64,
            as_u64(case, "/slices"),
            "{name}: slice count"
        );
        let expected: Vec<u64> = case["deltas"]
            .as_array()
            .expect("deltas")
            .iter()
            .map(|d| d.as_u64().expect("delta u64"))
            .collect();
        assert_eq!(deltas, expected, "{name}: deltas");
        let floor = std::cmp::min(total, slice_tokens);
        assert!(
            deltas.iter().all(|&d| d >= floor),
            "{name}: delta under floor"
        );
        assert!(
            *deltas.last().unwrap() < 2 * slice_tokens,
            "{name}: last delta bound"
        );
    }
}

/// The schedule refuses out-of-range inputs instead of panicking or allocating
/// unboundedly (client-reachable panics have stranded escrow before).
#[test]
fn slice_schedule_misuse_rejected() {
    assert!(
        slice_deltas(0, 1_000_000).is_err(),
        "zero total must be Err"
    );
    assert!(
        slice_deltas(10_000, 0).is_err(),
        "zero sliceTokens must be Err"
    );
    assert!(
        slice_deltas(u64::MAX, 1).is_err(),
        "huge total must be Err, not an allocation"
    );
}

// ---------------------------------------------------------------------------
// sig-digest.json — B.5 digest bytes, EIP-191 recovery, AND the node signer
// ---------------------------------------------------------------------------

#[test]
fn sig_digest_vector_recovery_and_signer_byte_equality() {
    let vec = load("sig-digest.json");
    let f = SliceSigFields {
        model_id: as_str(&vec, "/values/modelId").into(),
        template_hash: as_str(&vec, "/values/templateHash").into(),
        env_hash: as_str(&vec, "/values/envHash").into(),
        input_commitment: as_str(&vec, "/values/inputCommitment").into(),
        checkpoint_manifest_sha256: as_str(&vec, "/values/checkpointManifestSha256").into(),
        slice_index: as_u64(&vec, "/values/sliceIndex"),
        tokens_delta: as_u64(&vec, "/values/tokensDelta"),
        session_id: as_u64(&vec, "/values/sessionId"),
        host: as_str(&vec, "/values/host").into(),
        timestamp: as_u64(&vec, "/values/timestamp"),
    };
    let digest = sig_digest(&f).expect("digest");
    assert_eq!(
        format!("0x{}", hex::encode(digest)),
        as_str(&vec, "/sigDigest"),
        "sigDigest diverges from the TS reference"
    );

    // Recovery: verifyMessage(getBytes(digest), sig) === host.
    let sig = Signature::from_str(as_str(&vec, "/signature")).expect("signature");
    let recovered = sig
        .recover(RecoveryMessage::Data(digest.to_vec()))
        .expect("recover");
    let signer = Address::from_str(as_str(&vec, "/signer/address")).expect("address");
    assert_eq!(
        recovered, signer,
        "EIP-191 recovery must yield the vector signer"
    );

    // The NODE's signer must reproduce the vector signature BYTE-FOR-BYTE
    // (RFC 6979 deterministic ECDSA + the same \x19Ethereum Signed Message:\n32
    // prefix) — this is what proves sign_eip191_digest and ethers'
    // signMessage are the same scheme, not merely mutually recoverable.
    let key_hex = as_str(&vec, "/signer/privateKey").trim_start_matches("0x");
    let key_bytes: [u8; 32] = hex::decode(key_hex)
        .expect("key hex")
        .try_into()
        .expect("32 bytes");
    let node_sig = sign_eip191_digest(&key_bytes, digest).expect("node signer");
    assert_eq!(
        format!("0x{}", hex::encode(node_sig)),
        as_str(&vec, "/signature"),
        "node signer must reproduce the TS signature exactly"
    );
}

// ---------------------------------------------------------------------------
// manifests.json — D.2/D.3 canonical bytes + SHA256 + the D.1 splitter pins
// ---------------------------------------------------------------------------

#[test]
fn manifest_canonicalisation_vectors() {
    let vec = load("manifests.json");
    for kind in ["dataset", "adapter", "shiftedRemainder"] {
        let object = &vec[kind]["object"];
        assert_eq!(
            canonical_manifest_bytes(object),
            as_str(&vec, &format!("/{kind}/canonicalBytes")),
            "{kind}: canonical bytes diverge"
        );
        assert_eq!(
            canonical_manifest_sha256(object),
            as_str(&vec, &format!("/{kind}/manifestSha256")),
            "{kind}: canonical sha256 diverges"
        );
    }
    // D.1: no shard anywhere (dataset included) is an exact 262,144 multiple.
    let mut checked = 0;
    for kind in ["dataset", "adapter", "shiftedRemainder"] {
        let obj = &vec[kind]["object"];
        let shard_lists: Vec<&Value> = if kind == "dataset" {
            vec![&obj["shards"]]
        } else {
            obj["files"]
                .as_array()
                .unwrap()
                .iter()
                .map(|f| &f["shards"])
                .collect()
        };
        for shards in shard_lists {
            for shard in shards.as_array().unwrap() {
                let size = shard["sizeBytes"].as_u64().unwrap();
                assert_ne!(size % 262_144, 0, "{kind}: chunk-multiple shard {size}");
                checked += 1;
            }
        }
    }
    assert!(
        checked >= 15,
        "expected every vector shard checked, got {checked}"
    );

    // The v0.3.2 splitter disambiguation, pinned as shapes: an exact-multiple
    // remainder (524,288 = 2 × 262,144) splits into (remainder − 1) + 1 byte.
    let shifted = &vec["shiftedRemainder"]["object"]["files"][0];
    let sizes: Vec<u64> = shifted["shards"]
        .as_array()
        .unwrap()
        .iter()
        .map(|s| s["sizeBytes"].as_u64().unwrap())
        .collect();
    assert_eq!(
        sizes,
        vec![25_161_728, 524_287, 1],
        "shifted-remainder shard shape"
    );
    assert_eq!(
        sizes.iter().sum::<u64>(),
        shifted["sizeBytes"].as_u64().unwrap()
    );
}

// ---------------------------------------------------------------------------
// billing.json — C.1 maths through the production token function, four cases
// ---------------------------------------------------------------------------

#[test]
fn billing_vectors_all_cases() {
    let vec = load("billing.json");
    let min_deposit = as_u64(&vec, "/minDepositMicroUsdc");
    let cases = vec["cases"].as_object().expect("cases");
    assert_eq!(
        cases.len(),
        4,
        "worked + roundingBites + roundVsFloor + minFloorBinds"
    );
    for (name, case) in cases {
        let tokens = as_u64(case, "/trainingTokens");
        let price = as_u64(case, "/pricePerToken");
        let gross = tokens * price / 1000; // floor — PRICE_PRECISION = 1000
        assert_eq!(gross, as_u64(case, "/grossMicroUsdc"), "{name}: gross");
        let deposit = std::cmp::max(min_deposit, (gross * 105 + 99) / 100);
        assert_eq!(
            deposit,
            as_u64(case, "/depositMicroUsdc"),
            "{name}: deposit"
        );
    }
    // The discriminating properties that make these cases adversarial:
    let rb_gross = as_u64(&vec, "/cases/roundingBites/grossMicroUsdc");
    let rb_tokens = as_u64(&vec, "/cases/roundingBites/trainingTokens");
    let rb_price = as_u64(&vec, "/cases/roundingBites/pricePerToken");
    assert_ne!(
        rb_tokens * rb_price % 1000,
        0,
        "roundingBites: gross floor must bite"
    );
    assert_ne!(
        rb_gross * 105 % 100,
        0,
        "roundingBites: deposit ceil must differ from floor"
    );
    // roundVsFloor: the gross fraction must be >= .5 so a round-to-nearest
    // implementation diverges from floor on the gross itself (round-2 finding).
    let rvf_tokens = as_u64(&vec, "/cases/roundVsFloor/trainingTokens");
    let rvf_price = as_u64(&vec, "/cases/roundVsFloor/pricePerToken");
    assert!(
        rvf_tokens * rvf_price % 1000 >= 500,
        "roundVsFloor: gross fraction must be >= .5"
    );
    assert_eq!(
        as_u64(&vec, "/cases/minFloorBinds/depositMicroUsdc"),
        min_deposit,
        "minFloorBinds: the 0.5 USDC floor must be the binding branch"
    );
    // Worked case coherence THROUGH the production function, from the job.
    let commit_vec = load("input-commitment.json");
    let job: TrainingJob = serde_json::from_value(commit_vec["job"].clone()).unwrap();
    assert_eq!(
        training_tokens(job.dataset.declared_tokens, job.epochs).unwrap(),
        as_u64(&vec, "/cases/worked/trainingTokens"),
        "worked billing tokens must equal trainingTokens(vector job)"
    );
}

// ---------------------------------------------------------------------------
// Cross-file links (round-1: previously enforced by generator construction only)
// ---------------------------------------------------------------------------

#[test]
fn vector_cross_links() {
    let commit = load("input-commitment.json");
    let manifests = load("manifests.json");
    let sched = load("slice-schedule.json");
    let sig = load("sig-digest.json");

    // The commitment job's dataset hash IS the dataset manifest's hash.
    assert_eq!(
        as_str(&commit, "/job/dataset/manifestSha256"),
        as_str(&manifests, "/dataset/manifestSha256"),
        "commitment job ↔ dataset manifest sha"
    );
    // The commitment job's declared/epochs ARE the worked schedule case.
    assert_eq!(
        as_u64(&commit, "/job/dataset/declaredTokens"),
        as_u64(&sched, "/cases/worked/declaredTokens")
    );
    assert_eq!(
        as_u64(&commit, "/job/epochs"),
        as_u64(&sched, "/cases/worked/epochs")
    );
    // The sig vector embeds the commitment vector's output and job identity.
    assert_eq!(
        as_str(&sig, "/values/inputCommitment"),
        as_str(&commit, "/inputCommitment")
    );
    assert_eq!(
        as_str(&sig, "/values/templateHash"),
        as_str(&commit, "/job/templateHash")
    );
    // The sig vector's tokensDelta is the worked schedule's delta[0].
    assert_eq!(
        as_u64(&sig, "/values/tokensDelta"),
        sched
            .pointer("/cases/worked/deltas/0")
            .and_then(Value::as_u64)
            .expect("worked delta[0]")
    );
    // Dataset manifest's declaredTokens matches the commitment job's.
    assert_eq!(
        as_u64(&manifests, "/dataset/object/declaredTokens"),
        as_u64(&commit, "/job/dataset/declaredTokens")
    );
}
