# Copyright (c) 2025 Fabstir
# SPDX-License-Identifier: BUSL-1.1
services:
  # Enhanced S5 with permission fixes
  s5-enhanced-real:
    image: fabstir-llm-marketplace-s5-enhanced-dev:latest
    container_name: s5-enhanced-real
    user: "0:0"  # Run as root to avoid permission issues
    ports:
      - "5525:5522"
    environment:
      - NODE_ENV=production
      - S5_NODE_URL=https://s5.vup.cx
      - S5_SEED_PHRASE=${S5_SEED_PHRASE}
      - PORT=5522
      - ENABLE_MOCK=false
    env_file:
      - .env.real_s5
    volumes:
      - ~/dev/Fabstir/partners/S5/GitHub/s5.js:/home/developer/s5.js:cached
      - ./uploads:/home/developer/uploads
    working_dir: /home/developer/s5.js
    command: sh -c "if [ -f dist/index.js ]; then npm start; else npm install && npm run build && npm start; fi"
    networks:
      - fabstir-real
    restart: unless-stopped

  # Vector DB with S5 mock server URL configured
  vector-db-real:
    image: fabstir-vectordb-fabstir-ai-vector-db:latest
    container_name: vector-db-real
    ports:
      - "8081:8080"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgresql://postgres:postgres@postgres-real:5432/vectordb
      - S5_MOCK_SERVER_URL=http://s5-enhanced-real:5522  # Point to S5 service
      - STORAGE_MODE=mock  # Use mock mode for now
    volumes:
      - ~/dev/Fabstir/fabstir-vectordb:/workspace:cached
    working_dir: /workspace
    command: ./target/release/server
    networks:
      - fabstir-real
    depends_on:
      - postgres-real
      - s5-enhanced-real
    restart: unless-stopped

  postgres-real:
    image: postgres:14
    container_name: postgres-real
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectordb
    volumes:
      - postgres-real-data:/var/lib/postgresql/data
    networks:
      - fabstir-real
    restart: unless-stopped

networks:
  fabstir-real:
    driver: bridge

volumes:
  postgres-real-data:
