services:
  # Enhanced S5 with the new server wrapper
  s5-server:
    image: fabstir-llm-marketplace-s5-enhanced-dev:latest
    container_name: s5-server
    user: "0:0"
    ports:
      - "5525:5522"
    environment:
      - NODE_ENV=production
      - PORT=5522
      - S5_SEED_PHRASE=${S5_SEED_PHRASE}
    env_file:
      - .env.real_s5
    volumes:
      - ~/dev/Fabstir/partners/S5/GitHub/s5.js:/home/developer/s5.js:cached
    working_dir: /home/developer/s5.js
    command: sh -c "npm start || node dist/src/server.js"
    networks:
      - fabstir-real
    restart: unless-stopped

  # Vector DB (waiting for updates, using mock for now)
  vector-db-real:
    image: fabstir-vectordb-fabstir-ai-vector-db:latest
    container_name: vector-db-real
    ports:
      - "8081:8080"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgresql://postgres:postgres@postgres-real:5432/vectordb
      - S5_NODE_URL=http://s5-server:5522
      - S5_MOCK_SERVER_URL=http://s5-server:5522
      - STORAGE_MODE=mock  # Will change to real once vectordb is updated
    volumes:
      - ~/dev/Fabstir/fabstir-vectordb:/workspace:cached
    working_dir: /workspace
    command: ./target/release/server
    networks:
      - fabstir-real
    depends_on:
      - postgres-real
      - s5-server
    restart: unless-stopped

  postgres-real:
    image: postgres:14
    container_name: postgres-real
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectordb
    volumes:
      - postgres-real-data:/var/lib/postgresql/data
    networks:
      - fabstir-real
    restart: unless-stopped

networks:
  fabstir-real:
    driver: bridge

volumes:
  postgres-real-data:
